baseURL = "https://neppo.net/"
languageCode = "ja"
hasCJKLanguage = true
title = "ねっぽのゆるふわメモ"
theme = "hyde"

[permalinks]
blog = "/blog/:year/:month/:slug/"

[params]
themeColor = "theme-base-0d"
description = "ゆるふわエンジニアのゆるふわな活動記録"
disqusShortname = "neppo-net"
googleAnalytics = "UA-108252466-1"

[blackfriday]
hrefTargetBlank = true

[[menu.main]]
name = "twitter"
identifier = "twitter"
weight = -110
url = "https://twitter.com/jo7ueb"

[[menu.main]]
name = "GitHub"
identifier = "github"
weight = -100
url = "https://github.com/jo7ueb"

